name: AnyRouter 自动签到

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  
jobs:
  checkin:
    runs-on: windows-latest
    environment: production

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 安装 Playwright 浏览器
      run: |
        playwright install chromium
        playwright install-deps
        
    - name: 执行签到
      env:
        ANYROUTER_ACCOUNTS: ${{ secrets.ANYROUTER_ACCOUNTS }}
        DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
        FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
        WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
      run: |
        python checkin.py
        
    - name: 显示执行结果
      if: always()
      run: |
        echo "签到任务执行完成"
        echo "时间: $(Get-Date)"
